### ISSUE TITLE
ESLint error with react

### ISSUE THREAD

**Issue by tawfiknasser** [FACN4/Election-Day-App#28]
ESLint is not working with react , it shows error message while running our eslintrc file.
![selection_019](https://user-images.githubusercontent.com/36166288/45390962-e95e8400-b629-11e8-89cb-35933b34f8ae.png)

**Comment by MynahMarie** [comment]
So I looked into the eslint issues, I think some of the packages your team is using are creating some conflicts. After googling, I found a configuration that seems to work for getting rid of unwanted errors.

Here is step by step what I did:

- removed `airbnb` related eslint packages.
-  installed `babel-eslint` in the dev dependencies

In the `.eslintrc` file I changed the following:

- changed the `extends` key to `"eslint:recommended"`
- added `"es6": true` in the `env` object
- added `plugins`, `parser` and `parserOptions` keys
- `import/no-extraneous-dependencies`: changed value from `false` to `0`
- fixed `react/jsx-no-bind` to add the appropriate set of values (we still need to test these rules and see how they apply in the context of this project...)

Here is the contents of the edited `.eslintrc` file that seemed to work on my machine:

```
{
  "extends": "eslint:recommended",
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "plugins": [
    "react",
    "import"
  ],
  "parser": "babel-eslint",
  "parserOptions": {
    "sourceType": "module"
  },
  "rules": {
    "react/jsx-no-bind": [0, {
      "ignoreRefs": false,
      "allowArrowFunctions": true,
      "allowBind": false
    }],
    "no-unused-vars": "off",
    "import/no-extraneous-dependencies": 0,
    "no-unused-expressions": ["error", { "allowTernary": true }],
    "no-console": 0,
    "prefer-destructuring": [
      "error",
      {
        "array": false,
        "object": false
      }
    ]
  }
}
```
Let's see if this helps, maybe test it and let me know what you think. It would also be a good idea to add a script for eslint in package.json so that it's possible to test and lint the files easily 😀
